apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Values.deploy.name}}"
spec:
  replicas: {{ default 1 .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: flights-api
  template:
    metadata:
      labels:
        app: flights-api
    spec:
      containers:
        - image: "{{.Values.deploy.acrServer}}/hackfest/flights-api:{{.Values.deploy.imageTag}}"
          imagePullPolicy: Always
          name: flights-api
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: APPINSIGHTS_INSTRUMENTATIONKEY
              valueFrom:
                secretKeyRef:
                  name: app-insights-secret
                  key: appinsights
            - name: DATA_SERVICE_URI
              value: http://data-api.hackfest.svc.cluster.local:3009/
            - name: CACHE_SERVICE_URI
              value: http://cache-api.hackfest.svc.cluster.local:3006/       
          ports:
          - containerPort: {{.Values.deploy.containerPort}}
            protocol: TCP
      restartPolicy: Always
