name: service-tracker-ui
home: https://github.com/Azure/kubernetes-hackfest/tree/master/labs/build-application
version: 1.0
description: web app for GBB Kubernetes Hackfest
maintainers: 
  - name: chzbrgr71
    email: brianisrunning@gmail.com
